name: Deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - deploy # 해당 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        working-directory: ./front-end
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        working-directory: ./front-end
        run: npm ci

      - name: Build # React Build
        working-directory: ./front-end
        run: npm run build
        env:
          CI: ""

      - name: zip create
        # zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
        working-directory: ./front-end
        run: zip -qq -r ./build.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        working-directory: ./front-end
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://nemozone-deploy/build.zip

      - name: Deploy # Deploy to EC2
        working-directory: ./front-end
        run: aws deploy create-deployment
          --application-name nemozone-fe-auto-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name nemozone-fe
          --s3-location bucket=nemozone-deploy,key=build.zip,bundleType=zip
